INSERT INTO public.currency (code, name, symbol)
VALUES ('SHP', 'Saint Helena pound', '£'),
       ('XCD', 'Eastern Caribbean dollar', '$'),
       ('CHF', 'Swiss franc', 'Fr.'),
       ('SLL', 'Sierra Leonean leone', 'Le'),
       ('HUF', 'Hungarian forint', 'Ft'),
       ('TWD', 'New Taiwan dollar', '$'),
       ('XPF', 'CFP franc', '₣'),
       ('BBD', 'Barbadian dollar', '$'),
       ('NZD', 'New Zealand dollar', '$'),
       ('XOF', 'West African CFA franc', 'Fr'),
       ('TND', 'Tunisian dinar', 'د.ت'),
       ('EUR', 'Euro', '€'),
       ('IDR', 'Indonesian rupiah', 'Rp'),
       ('CVE', 'Cape Verdean escudo', 'Esc'),
       ('LAK', 'Lao kip', '₭'),
       ('USD', 'United States dollar', '$'),
       ('UGX', 'Ugandan shilling', 'Sh'),
       ('BIF', 'Burundian franc', 'Fr'),
       ('ZAR', 'South African rand', 'R'),
       ('LYD', 'Libyan dinar', 'ل.د'),
       ('MXN', 'Mexican peso', '$'),
       ('XAF', 'Central African CFA franc', 'Fr'),
       ('MKD', 'denar', 'den'),
       ('CNY', 'Chinese yuan', '¥'),
       ('YER', 'Yemeni rial', '﷼'),
       ('GBP', 'British pound', '£'),
       ('SBD', 'Solomon Islands dollar', '$'),
       ('NOK', 'krone', 'kr'),
       ('DKK', 'Danish krone', 'kr'),
       ('UZS', 'Uzbekistani soʻm', 'so''m'),
       ('EGP', 'Egyptian pound', '£'),
       ('LKR', 'Sri Lankan rupee', 'Rs  රු'),
       ('BDT', 'Bangladeshi taka', '৳'),
       ('PEN', 'Peruvian sol', 'S/ '),
       ('SGD', 'Singapore dollar', '$'),
       ('TRY', 'Turkish lira', '₺'),
       ('AFN', 'Afghan afghani', '؋'),
       ('AWG', 'Aruban florin', 'ƒ'),
       ('CKD', 'Cook Islands dollar', '$'),
       ('ZMW', 'Zambian kwacha', 'ZK'),
       ('AUD', 'Australian dollar', '$'),
       ('AZN', 'Azerbaijani manat', '₼'),
       ('DJF', 'Djiboutian franc', 'Fr'),
       ('KPW', 'North Korean won', '₩'),
       ('MUR', 'Mauritian rupee', '₨'),
       ('COP', 'Colombian peso', '$'),
       ('MAD', 'Moroccan dirham', 'د.م.'),
       ('DZD', 'Algerian dinar', 'د.ج'),
       ('SDG', 'Sudanese pound', 'ج.س'),
       ('FJD', 'Fijian dollar', '$'),
       ('NPR', 'Nepalese rupee', '₨'),
       ('GEL', 'lari', '₾'),
       ('PKR', 'Pakistani rupee', '₨'),
       ('BWP', 'Botswana pula', 'P'),
       ('LBP', 'Lebanese pound', 'ل.ل'),
       ('PGK', 'Papua New Guinean kina', 'K'),
       ('DOP', 'Dominican peso', '$'),
       ('QAR', 'Qatari riyal', 'ر.ق'),
       ('MGA', 'Malagasy ariary', 'Ar'),
       ('INR', 'Indian rupee', '₹'),
       ('SYP', 'Syrian pound', '£'),
       ('SZL', 'Swazi lilangeni', 'L'),
       ('PYG', 'Paraguayan guaraní', '₲'),
       ('UAH', 'Ukrainian hryvnia', '₴'),
       ('NAD', 'Namibian dollar', '$'),
       ('AED', 'United Arab Emirates dirham', 'د.إ'),
       ('BGN', 'Bulgarian lev', 'лв'),
       ('KHR', 'Cambodian riel', '៛'),
       ('IQD', 'Iraqi dinar', 'ع.د'),
       ('SEK', 'Swedish krona', 'kr'),
       ('CUC', 'Cuban convertible peso', '$'),
       ('KGS', 'Kyrgyzstani som', 'с'),
       ('RUB', 'Russian ruble', '₽'),
       ('MYR', 'Malaysian ringgit', 'RM'),
       ('STN', 'São Tomé and Príncipe dobra', 'Db'),
       ('CAD', 'Canadian dollar', '$'),
       ('MWK', 'Malawian kwacha', 'MK'),
       ('SAR', 'Saudi riyal', 'ر.س'),
       ('BAM', 'Bosnia and Herzegovina convertible mark', 'KM'),
       ('ETB', 'Ethiopian birr', 'Br'),
       ('OMR', 'Omani rial', 'ر.ع.'),
       ('MOP', 'Macanese pataca', 'P'),
       ('LSL', 'Lesotho loti', 'L'),
       ('ANG', 'Netherlands Antillean guilder', 'ƒ'),
       ('ISK', 'Icelandic króna', 'kr'),
       ('ARS', 'Argentine peso', '$'),
       ('CRC', 'Costa Rican colón', '₡'),
       ('THB', 'Thai baht', '฿'),
       ('HTG', 'Haitian gourde', 'G'),
       ('HNL', 'Honduran lempira', 'L'),
       ('BYN', 'Belarusian ruble', 'Br'),
       ('PHP', 'Philippine peso', '₱'),
       ('GIP', 'Gibraltar pound', '£'),
       ('GNF', 'Guinean franc', 'Fr'),
       ('BHD', 'Bahraini dinar', '.د.ب'),
       ('SRD', 'Surinamese dollar', '$'),
       ('CDF', 'Congolese franc', 'FC'),
       ('SOS', 'Somali shilling', 'Sh'),
       ('CZK', 'Czech koruna', 'Kč'),
       ('VUV', 'Vanuatu vatu', 'Vt'),
       ('KES', 'Kenyan shilling', 'Sh'),
       ('RWF', 'Rwandan franc', 'Fr'),
       ('RON', 'Romanian leu', 'lei'),
       ('TTD', 'Trinidad and Tobago dollar', '$'),
       ('GYD', 'Guyanese dollar', '$'),
       ('VND', 'Vietnamese đồng', '₫'),
       ('UYU', 'Uruguayan peso', '$'),
       ('HKD', 'Hong Kong dollar', '$'),
       ('TMT', 'Turkmenistan manat', 'm'),
       ('MZN', 'Mozambican metical', 'MT'),
       ('PAB', 'Panamanian balboa', 'B/.'),
       ('ERN', 'Eritrean nakfa', 'Nfk'),
       ('TZS', 'Tanzanian shilling', 'Sh'),
       ('KRW', 'South Korean won', '₩'),
       ('JOD', 'Jordanian dinar', 'د.ا'),
       ('MRU', 'Mauritanian ouguiya', 'UM'),
       ('AOA', 'Angolan kwanza', 'Kz'),
       ('KZT', 'Kazakhstani tenge', '₸'),
       ('MDL', 'Moldovan leu', 'L'),
       ('FKP', 'Falkland Islands pound', '£'),
       ('AMD', 'Armenian dram', '֏'),
       ('WST', 'Samoan tālā', 'T'),
       ('JPY', 'Japanese yen', '¥'),
       ('BOB', 'Bolivian boliviano', 'Bs.'),
       ('CLP', 'Chilean peso', '$'),
       ('BMD', 'Bermudian dollar', '$'),
       ('SCR', 'Seychellois rupee', '₨'),
       ('GTQ', 'Guatemalan quetzal', 'Q'),
       ('TJS', 'Tajikistani somoni', 'ЅМ'),
       ('GMD', 'dalasi', 'D'),
       ('NGN', 'Nigerian naira', '₦'),
       ('BSD', 'Bahamian dollar', '$'),
       ('KWD', 'Kuwaiti dinar', 'د.ك'),
       ('MVR', 'Maldivian rufiyaa', '.ރ'),
       ('SSP', 'South Sudanese pound', '£'),
       ('IRR', 'Iranian rial', '﷼'),
       ('ALL', 'Albanian lek', 'L'),
       ('BRL', 'Brazilian real', 'R$'),
       ('RSD', 'Serbian dinar', 'дин.'),
       ('BZD', 'Belize dollar', '$'),
       ('MMK', 'Burmese kyat', 'Ks'),
       ('BTN', 'Bhutanese ngultrum', 'Nu.'),
       ('VES', 'Venezuelan bolívar soberano', 'Bs.S.'),
       ('LRD', 'Liberian dollar', '$'),
       ('JMD', 'Jamaican dollar', '$'),
       ('PLN', 'Polish złoty', 'zł'),
       ('KYD', 'Cayman Islands dollar', '$'),
       ('BND', 'Brunei dollar', '$'),
       ('KMF', 'Comorian franc', 'Fr'),
       ('TOP', 'Tongan paʻanga', 'T$'),
       ('GHS', 'Ghanaian cedi', '₵'),
       ('ZWL', 'Zimbabwean dollar', '$'),
       ('MNT', 'Mongolian tögrög', '₮'),
       ('ILS', 'Israeli new shekel', '₪'),
       ('NIO', 'Nicaraguan córdoba', 'C$');

INSERT INTO public.country (name, official_name, code, currency)
VALUES ('South Georgia', 'South Georgia and the South Sandwich Islands', 'SGS',
        (SELECT id FROM public.currency WHERE code = 'SHP')),
       ('Grenada', 'Grenada', 'GRD', (SELECT id FROM public.currency WHERE code = 'XCD')),
       ('Switzerland', 'Swiss Confederation', 'CHE', (SELECT id FROM public.currency WHERE code = 'CHF')),
       ('Sierra Leone', 'Republic of Sierra Leone', 'SLE', (SELECT id FROM public.currency WHERE code = 'SLL')),
       ('Hungary', 'Hungary', 'HUN', (SELECT id FROM public.currency WHERE code = 'HUF')),
       ('Taiwan', 'Republic of China (Taiwan)', 'TWN', (SELECT id FROM public.currency WHERE code = 'TWD')),
       ('Wallis and Futuna', 'Territory of the Wallis and Futuna Islands', 'WLF',
        (SELECT id FROM public.currency WHERE code = 'XPF')),
       ('Barbados', 'Barbados', 'BRB', (SELECT id FROM public.currency WHERE code = 'BBD')),
       ('Pitcairn Islands', 'Pitcairn Group of Islands', 'PCN', (SELECT id FROM public.currency WHERE code = 'NZD')),
       ('Ivory Coast', 'Republic of Côte d''Ivoire', 'CIV', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('Tunisia', 'Tunisian Republic', 'TUN', (SELECT id FROM public.currency WHERE code = 'TND')),
       ('Italy', 'Italian Republic', 'ITA', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Benin', 'Republic of Benin', 'BEN', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('Indonesia', 'Republic of Indonesia', 'IDN', (SELECT id FROM public.currency WHERE code = 'IDR')),
       ('Cape Verde', 'Republic of Cabo Verde', 'CPV', (SELECT id FROM public.currency WHERE code = 'CVE')),
       ('Saint Kitts and Nevis', 'Federation of Saint Christopher and Nevis', 'KNA',
        (SELECT id FROM public.currency WHERE code = 'XCD')),
       ('Laos', 'Lao People''s Democratic Republic', 'LAO', (SELECT id FROM public.currency WHERE code = 'LAK')),
       ('Caribbean Netherlands', 'Bonaire, Sint Eustatius and Saba', 'BES',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Uganda', 'Republic of Uganda', 'UGA', (SELECT id FROM public.currency WHERE code = 'UGX')),
       ('Andorra', 'Principality of Andorra', 'AND', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Burundi', 'Republic of Burundi', 'BDI', (SELECT id FROM public.currency WHERE code = 'BIF')),
       ('South Africa', 'Republic of South Africa', 'ZAF', (SELECT id FROM public.currency WHERE code = 'ZAR')),
       ('France', 'French Republic', 'FRA', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Libya', 'State of Libya', 'LBY', (SELECT id FROM public.currency WHERE code = 'LYD')),
       ('Mexico', 'United Mexican States', 'MEX', (SELECT id FROM public.currency WHERE code = 'MXN')),
       ('Gabon', 'Gabonese Republic', 'GAB', (SELECT id FROM public.currency WHERE code = 'XAF')),
       ('Northern Mariana Islands', 'Commonwealth of the Northern Mariana Islands', 'MNP',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('North Macedonia', 'Republic of North Macedonia', 'MKD', (SELECT id FROM public.currency WHERE code = 'MKD')),
       ('China', 'People''s Republic of China', 'CHN', (SELECT id FROM public.currency WHERE code = 'CNY')),
       ('Yemen', 'Republic of Yemen', 'YEM', (SELECT id FROM public.currency WHERE code = 'YER')),
       ('Saint Barthélemy', 'Collectivity of Saint Barthélemy', 'BLM',
        (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Guernsey', 'Bailiwick of Guernsey', 'GGY', (SELECT id FROM public.currency WHERE code = 'GBP')),
       ('Solomon Islands', 'Solomon Islands', 'SLB', (SELECT id FROM public.currency WHERE code = 'SBD')),
       ('Svalbard and Jan Mayen', 'Svalbard og Jan Mayen', 'SJM', (SELECT id FROM public.currency WHERE code = 'NOK')),
       ('Faroe Islands', 'Faroe Islands', 'FRO', (SELECT id FROM public.currency WHERE code = 'DKK')),
       ('Uzbekistan', 'Republic of Uzbekistan', 'UZB', (SELECT id FROM public.currency WHERE code = 'UZS')),
       ('Egypt', 'Arab Republic of Egypt', 'EGY', (SELECT id FROM public.currency WHERE code = 'EGP')),
       ('Senegal', 'Republic of Senegal', 'SEN', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('Sri Lanka', 'Democratic Socialist Republic of Sri Lanka', 'LKA',
        (SELECT id FROM public.currency WHERE code = 'LKR')),
       ('Palestine', 'State of Palestine', 'PSE', (SELECT id FROM public.currency WHERE code = 'EGP')),
       ('Bangladesh', 'People''s Republic of Bangladesh', 'BGD', (SELECT id FROM public.currency WHERE code = 'BDT')),
       ('Peru', 'Republic of Peru', 'PER', (SELECT id FROM public.currency WHERE code = 'PEN')),
       ('Singapore', 'Republic of Singapore', 'SGP', (SELECT id FROM public.currency WHERE code = 'SGD')),
       ('Turkey', 'Republic of Turkey', 'TUR', (SELECT id FROM public.currency WHERE code = 'TRY')),
       ('Afghanistan', 'Islamic Republic of Afghanistan', 'AFG', (SELECT id FROM public.currency WHERE code = 'AFN')),
       ('Aruba', 'Aruba', 'ABW', (SELECT id FROM public.currency WHERE code = 'AWG')),
       ('Cook Islands', 'Cook Islands', 'COK', (SELECT id FROM public.currency WHERE code = 'CKD')),
       ('United Kingdom', 'United Kingdom of Great Britain and Northern Ireland', 'GBR',
        (SELECT id FROM public.currency WHERE code = 'GBP')),
       ('Zambia', 'Republic of Zambia', 'ZMB', (SELECT id FROM public.currency WHERE code = 'ZMW')),
       ('Finland', 'Republic of Finland', 'FIN', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Niger', 'Republic of Niger', 'NER', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('Christmas Island', 'Territory of Christmas Island', 'CXR',
        (SELECT id FROM public.currency WHERE code = 'AUD')),
       ('Tokelau', 'Tokelau', 'TKL', (SELECT id FROM public.currency WHERE code = 'NZD')),
       ('Guinea-Bissau', 'Republic of Guinea-Bissau', 'GNB', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('Azerbaijan', 'Republic of Azerbaijan', 'AZE', (SELECT id FROM public.currency WHERE code = 'AZN')),
       ('Réunion', 'Réunion Island', 'REU', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Djibouti', 'Republic of Djibouti', 'DJI', (SELECT id FROM public.currency WHERE code = 'DJF')),
       ('North Korea', 'Democratic People''s Republic of Korea', 'PRK',
        (SELECT id FROM public.currency WHERE code = 'KPW')),
       ('Mauritius', 'Republic of Mauritius', 'MUS', (SELECT id FROM public.currency WHERE code = 'MUR')),
       ('Montserrat', 'Montserrat', 'MSR', (SELECT id FROM public.currency WHERE code = 'XCD')),
       ('United States Virgin Islands', 'Virgin Islands of the United States', 'VIR',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Colombia', 'Republic of Colombia', 'COL', (SELECT id FROM public.currency WHERE code = 'COP')),
       ('Greece', 'Hellenic Republic', 'GRC', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Croatia', 'Republic of Croatia', 'HRV', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Morocco', 'Kingdom of Morocco', 'MAR', (SELECT id FROM public.currency WHERE code = 'MAD')),
       ('Algeria', 'People''s Democratic Republic of Algeria', 'DZA',
        (SELECT id FROM public.currency WHERE code = 'DZD')),
       ('Netherlands', 'Kingdom of the Netherlands', 'NLD', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Sudan', 'Republic of the Sudan', 'SDN', (SELECT id FROM public.currency WHERE code = 'SDG')),
       ('Fiji', 'Republic of Fiji', 'FJI', (SELECT id FROM public.currency WHERE code = 'FJD')),
       ('Liechtenstein', 'Principality of Liechtenstein', 'LIE', (SELECT id FROM public.currency WHERE code = 'CHF')),
       ('Nepal', 'Federal Democratic Republic of Nepal', 'NPL', (SELECT id FROM public.currency WHERE code = 'NPR')),
       ('Puerto Rico', 'Commonwealth of Puerto Rico', 'PRI', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Georgia', 'Georgia', 'GEO', (SELECT id FROM public.currency WHERE code = 'GEL')),
       ('Pakistan', 'Islamic Republic of Pakistan', 'PAK', (SELECT id FROM public.currency WHERE code = 'PKR')),
       ('Monaco', 'Principality of Monaco', 'MCO', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Botswana', 'Republic of Botswana', 'BWA', (SELECT id FROM public.currency WHERE code = 'BWP')),
       ('Lebanon', 'Lebanese Republic', 'LBN', (SELECT id FROM public.currency WHERE code = 'LBP')),
       ('Papua New Guinea', 'Independent State of Papua New Guinea', 'PNG',
        (SELECT id FROM public.currency WHERE code = 'PGK')),
       ('Mayotte', 'Department of Mayotte', 'MYT', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Dominican Republic', 'Dominican Republic', 'DOM', (SELECT id FROM public.currency WHERE code = 'DOP')),
       ('Norfolk Island', 'Territory of Norfolk Island', 'NFK', (SELECT id FROM public.currency WHERE code = 'AUD')),
       ('Qatar', 'State of Qatar', 'QAT', (SELECT id FROM public.currency WHERE code = 'QAR')),
       ('Madagascar', 'Republic of Madagascar', 'MDG', (SELECT id FROM public.currency WHERE code = 'MGA')),
       ('India', 'Republic of India', 'IND', (SELECT id FROM public.currency WHERE code = 'INR')),
       ('Syria', 'Syrian Arab Republic', 'SYR', (SELECT id FROM public.currency WHERE code = 'SYP')),
       ('Montenegro', 'Montenegro', 'MNE', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Eswatini', 'Kingdom of Eswatini', 'SWZ', (SELECT id FROM public.currency WHERE code = 'SZL')),
       ('Paraguay', 'Republic of Paraguay', 'PRY', (SELECT id FROM public.currency WHERE code = 'PYG')),
       ('El Salvador', 'Republic of El Salvador', 'SLV', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Ukraine', 'Ukraine', 'UKR', (SELECT id FROM public.currency WHERE code = 'UAH')),
       ('Isle of Man', 'Isle of Man', 'IMN', (SELECT id FROM public.currency WHERE code = 'GBP')),
       ('Namibia', 'Republic of Namibia', 'NAM', (SELECT id FROM public.currency WHERE code = 'NAD')),
       ('United Arab Emirates', 'United Arab Emirates', 'ARE', (SELECT id FROM public.currency WHERE code = 'AED')),
       ('Bulgaria', 'Republic of Bulgaria', 'BGR', (SELECT id FROM public.currency WHERE code = 'BGN')),
       ('Greenland', 'Greenland', 'GRL', (SELECT id FROM public.currency WHERE code = 'DKK')),
       ('Germany', 'Federal Republic of Germany', 'DEU', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Cambodia', 'Kingdom of Cambodia', 'KHM', (SELECT id FROM public.currency WHERE code = 'KHR')),
       ('Iraq', 'Republic of Iraq', 'IRQ', (SELECT id FROM public.currency WHERE code = 'IQD')),
       ('French Southern and Antarctic Lands', 'Territory of the French Southern and Antarctic Lands', 'ATF',
        (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Sweden', 'Kingdom of Sweden', 'SWE', (SELECT id FROM public.currency WHERE code = 'SEK')),
       ('Cuba', 'Republic of Cuba', 'CUB', (SELECT id FROM public.currency WHERE code = 'CUC')),
       ('Kyrgyzstan', 'Kyrgyz Republic', 'KGZ', (SELECT id FROM public.currency WHERE code = 'KGS')),
       ('Russia', 'Russian Federation', 'RUS', (SELECT id FROM public.currency WHERE code = 'RUB')),
       ('Malaysia', 'Malaysia', 'MYS', (SELECT id FROM public.currency WHERE code = 'MYR')),
       ('São Tomé and Príncipe', 'Democratic Republic of São Tomé and Príncipe', 'STP',
        (SELECT id FROM public.currency WHERE code = 'STN')),
       ('Cyprus', 'Republic of Cyprus', 'CYP', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Canada', 'Canada', 'CAN', (SELECT id FROM public.currency WHERE code = 'CAD')),
       ('Malawi', 'Republic of Malawi', 'MWI', (SELECT id FROM public.currency WHERE code = 'MWK')),
       ('Saudi Arabia', 'Kingdom of Saudi Arabia', 'SAU', (SELECT id FROM public.currency WHERE code = 'SAR')),
       ('Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BIH', (SELECT id FROM public.currency WHERE code = 'BAM')),
       ('Ethiopia', 'Federal Democratic Republic of Ethiopia', 'ETH',
        (SELECT id FROM public.currency WHERE code = 'ETB')),
       ('Spain', 'Kingdom of Spain', 'ESP', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Slovenia', 'Republic of Slovenia', 'SVN', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Oman', 'Sultanate of Oman', 'OMN', (SELECT id FROM public.currency WHERE code = 'OMR')),
       ('Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 'SPM',
        (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Macau', 'Macao Special Administrative Region of the People''s Republic of China', 'MAC',
        (SELECT id FROM public.currency WHERE code = 'MOP')),
       ('San Marino', 'Republic of San Marino', 'SMR', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Lesotho', 'Kingdom of Lesotho', 'LSO', (SELECT id FROM public.currency WHERE code = 'LSL')),
       ('Marshall Islands', 'Republic of the Marshall Islands', 'MHL',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Sint Maarten', 'Sint Maarten', 'SXM', (SELECT id FROM public.currency WHERE code = 'ANG')),
       ('Iceland', 'Iceland', 'ISL', (SELECT id FROM public.currency WHERE code = 'ISK')),
       ('Luxembourg', 'Grand Duchy of Luxembourg', 'LUX', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Argentina', 'Argentine Republic', 'ARG', (SELECT id FROM public.currency WHERE code = 'ARS')),
       ('Turks and Caicos Islands', 'Turks and Caicos Islands', 'TCA',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Nauru', 'Republic of Nauru', 'NRU', (SELECT id FROM public.currency WHERE code = 'AUD')),
       ('Cocos (Keeling) Islands', 'Territory of the Cocos (Keeling) Islands', 'CCK',
        (SELECT id FROM public.currency WHERE code = 'AUD')),
       ('Western Sahara', 'Sahrawi Arab Democratic Republic', 'ESH',
        (SELECT id FROM public.currency WHERE code = 'DZD')),
       ('Dominica', 'Commonwealth of Dominica', 'DMA', (SELECT id FROM public.currency WHERE code = 'XCD')),
       ('Costa Rica', 'Republic of Costa Rica', 'CRI', (SELECT id FROM public.currency WHERE code = 'CRC')),
       ('Australia', 'Commonwealth of Australia', 'AUS', (SELECT id FROM public.currency WHERE code = 'AUD')),
       ('Thailand', 'Kingdom of Thailand', 'THA', (SELECT id FROM public.currency WHERE code = 'THB')),
       ('Haiti', 'Republic of Haiti', 'HTI', (SELECT id FROM public.currency WHERE code = 'HTG')),
       ('Tuvalu', 'Tuvalu', 'TUV', (SELECT id FROM public.currency WHERE code = 'AUD')),
       ('Honduras', 'Republic of Honduras', 'HND', (SELECT id FROM public.currency WHERE code = 'HNL')),
       ('Equatorial Guinea', 'Republic of Equatorial Guinea', 'GNQ',
        (SELECT id FROM public.currency WHERE code = 'XAF')),
       ('Saint Lucia', 'Saint Lucia', 'LCA', (SELECT id FROM public.currency WHERE code = 'XCD')),
       ('French Polynesia', 'French Polynesia', 'PYF', (SELECT id FROM public.currency WHERE code = 'XPF')),
       ('Belarus', 'Republic of Belarus', 'BLR', (SELECT id FROM public.currency WHERE code = 'BYN')),
       ('Latvia', 'Republic of Latvia', 'LVA', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Palau', 'Republic of Palau', 'PLW', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Guadeloupe', 'Guadeloupe', 'GLP', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Philippines', 'Republic of the Philippines', 'PHL', (SELECT id FROM public.currency WHERE code = 'PHP')),
       ('Gibraltar', 'Gibraltar', 'GIB', (SELECT id FROM public.currency WHERE code = 'GIP')),
       ('Denmark', 'Kingdom of Denmark', 'DNK', (SELECT id FROM public.currency WHERE code = 'DKK')),
       ('Cameroon', 'Republic of Cameroon', 'CMR', (SELECT id FROM public.currency WHERE code = 'XAF')),
       ('Guinea', 'Republic of Guinea', 'GIN', (SELECT id FROM public.currency WHERE code = 'GNF')),
       ('Bahrain', 'Kingdom of Bahrain', 'BHR', (SELECT id FROM public.currency WHERE code = 'BHD')),
       ('Suriname', 'Republic of Suriname', 'SUR', (SELECT id FROM public.currency WHERE code = 'SRD')),
       ('DR Congo', 'Democratic Republic of the Congo', 'COD', (SELECT id FROM public.currency WHERE code = 'CDF')),
       ('Somalia', 'Federal Republic of Somalia', 'SOM', (SELECT id FROM public.currency WHERE code = 'SOS')),
       ('Czechia', 'Czech Republic', 'CZE', (SELECT id FROM public.currency WHERE code = 'CZK')),
       ('New Caledonia', 'New Caledonia', 'NCL', (SELECT id FROM public.currency WHERE code = 'XPF')),
       ('Vanuatu', 'Republic of Vanuatu', 'VUT', (SELECT id FROM public.currency WHERE code = 'VUV')),
       ('Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN',
        (SELECT id FROM public.currency WHERE code = 'GBP')),
       ('Togo', 'Togolese Republic', 'TGO', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('British Virgin Islands', 'Virgin Islands', 'VGB', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Kenya', 'Republic of Kenya', 'KEN', (SELECT id FROM public.currency WHERE code = 'KES')),
       ('Niue', 'Niue', 'NIU', (SELECT id FROM public.currency WHERE code = 'NZD')),
       ('Rwanda', 'Republic of Rwanda', 'RWA', (SELECT id FROM public.currency WHERE code = 'RWF')),
       ('Estonia', 'Republic of Estonia', 'EST', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Romania', 'Romania', 'ROU', (SELECT id FROM public.currency WHERE code = 'RON')),
       ('Trinidad and Tobago', 'Republic of Trinidad and Tobago', 'TTO',
        (SELECT id FROM public.currency WHERE code = 'TTD')),
       ('Guyana', 'Co-operative Republic of Guyana', 'GUY', (SELECT id FROM public.currency WHERE code = 'GYD')),
       ('Timor-Leste', 'Democratic Republic of Timor-Leste', 'TLS',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Vietnam', 'Socialist Republic of Vietnam', 'VNM', (SELECT id FROM public.currency WHERE code = 'VND')),
       ('Uruguay', 'Oriental Republic of Uruguay', 'URY', (SELECT id FROM public.currency WHERE code = 'UYU')),
       ('Vatican City', 'Vatican City State', 'VAT', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Hong Kong', 'Hong Kong Special Administrative Region of the People''s Republic of China', 'HKG',
        (SELECT id FROM public.currency WHERE code = 'HKD')),
       ('Austria', 'Republic of Austria', 'AUT', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Antigua and Barbuda', 'Antigua and Barbuda', 'ATG', (SELECT id FROM public.currency WHERE code = 'XCD')),
       ('Turkmenistan', 'Turkmenistan', 'TKM', (SELECT id FROM public.currency WHERE code = 'TMT')),
       ('Mozambique', 'Republic of Mozambique', 'MOZ', (SELECT id FROM public.currency WHERE code = 'MZN')),
       ('Panama', 'Republic of Panama', 'PAN', (SELECT id FROM public.currency WHERE code = 'PAB')),
       ('Micronesia', 'Federated States of Micronesia', 'FSM', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Ireland', 'Republic of Ireland', 'IRL', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Curaçao', 'Country of Curaçao', 'CUW', (SELECT id FROM public.currency WHERE code = 'ANG')),
       ('French Guiana', 'Guiana', 'GUF', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Norway', 'Kingdom of Norway', 'NOR', (SELECT id FROM public.currency WHERE code = 'NOK')),
       ('Åland Islands', 'Åland Islands', 'ALA', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Central African Republic', 'Central African Republic', 'CAF',
        (SELECT id FROM public.currency WHERE code = 'XAF')),
       ('Burkina Faso', 'Burkina Faso', 'BFA', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('Eritrea', 'State of Eritrea', 'ERI', (SELECT id FROM public.currency WHERE code = 'ERN')),
       ('Tanzania', 'United Republic of Tanzania', 'TZA', (SELECT id FROM public.currency WHERE code = 'TZS')),
       ('South Korea', 'Republic of Korea', 'KOR', (SELECT id FROM public.currency WHERE code = 'KRW')),
       ('Jordan', 'Hashemite Kingdom of Jordan', 'JOR', (SELECT id FROM public.currency WHERE code = 'JOD')),
       ('Mauritania', 'Islamic Republic of Mauritania', 'MRT', (SELECT id FROM public.currency WHERE code = 'MRU')),
       ('Lithuania', 'Republic of Lithuania', 'LTU', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'UMI',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Slovakia', 'Slovak Republic', 'SVK', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Angola', 'Republic of Angola', 'AGO', (SELECT id FROM public.currency WHERE code = 'AOA')),
       ('Kazakhstan', 'Republic of Kazakhstan', 'KAZ', (SELECT id FROM public.currency WHERE code = 'KZT')),
       ('Moldova', 'Republic of Moldova', 'MDA', (SELECT id FROM public.currency WHERE code = 'MDL')),
       ('Mali', 'Republic of Mali', 'MLI', (SELECT id FROM public.currency WHERE code = 'XOF')),
       ('Falkland Islands', 'Falkland Islands', 'FLK', (SELECT id FROM public.currency WHERE code = 'FKP')),
       ('Armenia', 'Republic of Armenia', 'ARM', (SELECT id FROM public.currency WHERE code = 'AMD')),
       ('Samoa', 'Independent State of Samoa', 'WSM', (SELECT id FROM public.currency WHERE code = 'WST')),
       ('Jersey', 'Bailiwick of Jersey', 'JEY', (SELECT id FROM public.currency WHERE code = 'GBP')),
       ('Japan', 'Japan', 'JPN', (SELECT id FROM public.currency WHERE code = 'JPY')),
       ('Bolivia', 'Plurinational State of Bolivia', 'BOL', (SELECT id FROM public.currency WHERE code = 'BOB')),
       ('Chile', 'Republic of Chile', 'CHL', (SELECT id FROM public.currency WHERE code = 'CLP')),
       ('United States', 'United States of America', 'USA', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VCT',
        (SELECT id FROM public.currency WHERE code = 'XCD')),
       ('Bermuda', 'Bermuda', 'BMU', (SELECT id FROM public.currency WHERE code = 'BMD')),
       ('Seychelles', 'Republic of Seychelles', 'SYC', (SELECT id FROM public.currency WHERE code = 'SCR')),
       ('British Indian Ocean Territory', 'British Indian Ocean Territory', 'IOT',
        (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Guatemala', 'Republic of Guatemala', 'GTM', (SELECT id FROM public.currency WHERE code = 'GTQ')),
       ('Ecuador', 'Republic of Ecuador', 'ECU', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Martinique', 'Martinique', 'MTQ', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Tajikistan', 'Republic of Tajikistan', 'TJK', (SELECT id FROM public.currency WHERE code = 'TJS')),
       ('Malta', 'Republic of Malta', 'MLT', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Gambia', 'Republic of the Gambia', 'GMB', (SELECT id FROM public.currency WHERE code = 'GMD')),
       ('Nigeria', 'Federal Republic of Nigeria', 'NGA', (SELECT id FROM public.currency WHERE code = 'NGN')),
       ('Bahamas', 'Commonwealth of the Bahamas', 'BHS', (SELECT id FROM public.currency WHERE code = 'BSD')),
       ('Kosovo', 'Republic of Kosovo', 'UNK', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Kuwait', 'State of Kuwait', 'KWT', (SELECT id FROM public.currency WHERE code = 'KWD')),
       ('Maldives', 'Republic of the Maldives', 'MDV', (SELECT id FROM public.currency WHERE code = 'MVR')),
       ('South Sudan', 'Republic of South Sudan', 'SSD', (SELECT id FROM public.currency WHERE code = 'SSP')),
       ('Iran', 'Islamic Republic of Iran', 'IRN', (SELECT id FROM public.currency WHERE code = 'IRR')),
       ('Albania', 'Republic of Albania', 'ALB', (SELECT id FROM public.currency WHERE code = 'ALL')),
       ('Brazil', 'Federative Republic of Brazil', 'BRA', (SELECT id FROM public.currency WHERE code = 'BRL')),
       ('Serbia', 'Republic of Serbia', 'SRB', (SELECT id FROM public.currency WHERE code = 'RSD')),
       ('Belize', 'Belize', 'BLZ', (SELECT id FROM public.currency WHERE code = 'BZD')),
       ('Myanmar', 'Republic of the Union of Myanmar', 'MMR', (SELECT id FROM public.currency WHERE code = 'MMK')),
       ('Bhutan', 'Kingdom of Bhutan', 'BTN', (SELECT id FROM public.currency WHERE code = 'BTN')),
       ('Venezuela', 'Bolivarian Republic of Venezuela', 'VEN', (SELECT id FROM public.currency WHERE code = 'VES')),
       ('Liberia', 'Republic of Liberia', 'LBR', (SELECT id FROM public.currency WHERE code = 'LRD')),
       ('Jamaica', 'Jamaica', 'JAM', (SELECT id FROM public.currency WHERE code = 'JMD')),
       ('Poland', 'Republic of Poland', 'POL', (SELECT id FROM public.currency WHERE code = 'PLN')),
       ('Cayman Islands', 'Cayman Islands', 'CYM', (SELECT id FROM public.currency WHERE code = 'KYD')),
       ('Brunei', 'Nation of Brunei, Abode of Peace', 'BRN', (SELECT id FROM public.currency WHERE code = 'BND')),
       ('Comoros', 'Union of the Comoros', 'COM', (SELECT id FROM public.currency WHERE code = 'KMF')),
       ('Guam', 'Guam', 'GUM', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Tonga', 'Kingdom of Tonga', 'TON', (SELECT id FROM public.currency WHERE code = 'TOP')),
       ('Kiribati', 'Independent and Sovereign Republic of Kiribati', 'KIR',
        (SELECT id FROM public.currency WHERE code = 'AUD')),
       ('Ghana', 'Republic of Ghana', 'GHA', (SELECT id FROM public.currency WHERE code = 'GHS')),
       ('Chad', 'Republic of Chad', 'TCD', (SELECT id FROM public.currency WHERE code = 'XAF')),
       ('Zimbabwe', 'Republic of Zimbabwe', 'ZWE', (SELECT id FROM public.currency WHERE code = 'ZWL')),
       ('Saint Martin', 'Saint Martin', 'MAF', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Mongolia', 'Mongolia', 'MNG', (SELECT id FROM public.currency WHERE code = 'MNT')),
       ('Portugal', 'Portuguese Republic', 'PRT', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('American Samoa', 'American Samoa', 'ASM', (SELECT id FROM public.currency WHERE code = 'USD')),
       ('Republic of the Congo', 'Republic of the Congo', 'COG', (SELECT id FROM public.currency WHERE code = 'XAF')),
       ('Belgium', 'Kingdom of Belgium', 'BEL', (SELECT id FROM public.currency WHERE code = 'EUR')),
       ('Israel', 'State of Israel', 'ISR', (SELECT id FROM public.currency WHERE code = 'ILS')),
       ('New Zealand', 'New Zealand', 'NZL', (SELECT id FROM public.currency WHERE code = 'NZD')),
       ('Nicaragua', 'Republic of Nicaragua', 'NIC', (SELECT id FROM public.currency WHERE code = 'NIO')),
       ('Anguilla', 'Anguilla', 'AIA', (SELECT id FROM public.currency WHERE code = 'XCD'));

