create table "public"."city" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "country" bigint not null
);


alter table "public"."city" enable row level security;

CREATE UNIQUE INDEX city_pkey ON public.city USING btree (id);

alter table "public"."city" add constraint "city_pkey" PRIMARY KEY using index "city_pkey";

alter table "public"."city" add constraint "city_country_fkey" FOREIGN KEY (country) REFERENCES country(id) not valid;

alter table "public"."city" validate constraint "city_country_fkey";

grant delete on table "public"."city" to "anon";

grant insert on table "public"."city" to "anon";

grant references on table "public"."city" to "anon";

grant select on table "public"."city" to "anon";

grant trigger on table "public"."city" to "anon";

grant truncate on table "public"."city" to "anon";

grant update on table "public"."city" to "anon";

grant delete on table "public"."city" to "authenticated";

grant insert on table "public"."city" to "authenticated";

grant references on table "public"."city" to "authenticated";

grant select on table "public"."city" to "authenticated";

grant trigger on table "public"."city" to "authenticated";

grant truncate on table "public"."city" to "authenticated";

grant update on table "public"."city" to "authenticated";

grant delete on table "public"."city" to "service_role";

grant insert on table "public"."city" to "service_role";

grant references on table "public"."city" to "service_role";

grant select on table "public"."city" to "service_role";

grant trigger on table "public"."city" to "service_role";

grant truncate on table "public"."city" to "service_role";

grant update on table "public"."city" to "service_role";


